chore: do some cleanup for web integration tests

diff --git a/melos.yaml b/melos.yaml
--- a/melos.yaml
+++ b/melos.yaml
@@ -112,9 +112,18 @@ scripts:
       dirExists: 
         - integration_test
         - ios
+  # for reference: https://github.com/firebase/flutterfire/blob/d41e30a808b47458d7ebd402862bcd55d8563ccb/.github/workflows/e2e_tests.yaml#L281-L289
   integration_test:chrome:
     name: Flutter Chrome Integration tests
-    exec: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d chrome --dart-define=CI=true | tee output.log
+    exec: |
+      flutter drive --driver=./test_driver/integration_test.dart --target=./integration_test/app_test.dart -d chrome --dart-define=CI=true | tee output.log
+      # We have to check the output for failed tests matching the string "[E]"
+      output=$(<output.log)
+      if [[ "$output" =~ \[E\] ]]; then
+      # You will see "All tests passed." in the logs even when tests failed.
+      echo "All tests did not pass. Please check the logs for more information."
+      exit 1
+      fi
     packageFilters:
       flutter: true
       dirExists:
