revert refactor

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -164,23 +164,35 @@ jobs:
           name: ios-coverage.info
           path: packages/oidc/example/ios-coverage.info
   web:
+    strategy:
+      fail-fast: false
+      matrix:
+        working-directory: ["packages/oidc/example"]
     runs-on: ubuntu-latest
     timeout-minutes: 15
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
       - name: Set up Environment
-        uses: ./.github/actions/integration_test_base
-        with:
-          channel: master
-          flutter-version: ''
-      - name: Run Chromedriver
+        uses: ./.github/actions/integration_test_base        
+      # for reference: https://github.com/firebase/flutterfire/blob/d41e30a808b47458d7ebd402862bcd55d8563ccb/.github/workflows/e2e_tests.yaml#L281-L289
+      - name: Run Web Integration Tests
+        working-directory: ${{ matrix.working-directory }}
         run: |
+          # first we run chromedriver on port 4444 and Xvfb
           export DISPLAY=:99
           chromedriver --port=4444 --trace-buffer-size=100000 &
           sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
-      - name: Run Web Integration Tests        
-        run: melos run integration_test:chrome
+          
+          # then we start flutter drive
+          flutter drive --driver=./test_driver/integration_test.dart --target=./integration_test/app_test.dart -d chrome --dart-define=CI=true | tee output.log
+          # We have to check the output for failed tests matching the string "[E]"
+          output=$(<output.log)
+          if [[ "$output" =~ \[E\] ]]; then
+          # You will see "All tests passed." in the logs even when tests failed.
+          echo "All tests did not pass. Please check the logs for more information."
+          exit 1
+          fi
         shell: bash
 
       # web has no test coverage for now  
