better logs for chromedriver

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -172,10 +172,22 @@ jobs:
         uses: ./.github/actions/integration_test_base      
       - name: Run Chromedriver
         uses: nanasess/setup-chromedriver@v2
-      - run: chromedriver --port=4444 --trace-buffer-size=100000 & sleep 5          
+      - run: chromedriver --verbose --port=4444 --trace-buffer-size=100000 | tee chromedriver.log & sleep 5          
         name: run chrome driver
       - name: Run Web Integration Tests
         run: melos run integration_test:chrome
+      # for reference: https://github.com/firebase/flutterfire/blob/d41e30a808b47458d7ebd402862bcd55d8563ccb/.github/workflows/e2e_tests.yaml#L281-L289
+      - name: Ensure all tests are actually passing
+        run: |
+          # We have to check the output for failed tests matching the string "[E]"
+          output=$(<output.log)
+          if [[ "$output" =~ \[E\] ]]; then
+          # You will see "All tests passed." in the logs even when tests failed.
+          echo "All tests did not pass. Please check the logs for more information."
+          exit 1
+          fi
+        shell: bash
+
       # web has no test coverage for now  
       # - name: Upload Coverage Report
       #   uses: actions/upload-artifact@v4
